### ISSUE TITLE
Console highlighting doesn't work

### ISSUE THREAD

**Issue by FichteFoll** [Kronuz/Kronuz-Theme#2]
I just installed this theme on a portable ST instance and the console is not colored (neither from the color scheme nor with syntax highlighting).

I followed the readme instructions (installed manually, set the theme and color_scheme settings and restarted), but the console and console input widgets are still dark on bright.

I also tried renaming `Widget.sublime-settings` to `Widget - Kronuz.sublime-settings` (which should have a higher precedence) to no avail. Am I doing something wrong or does this Just Not Work?

![2016-06-23_17 05 10](https://cloud.githubusercontent.com/assets/931051/16308309/c55573b4-3964-11e6-953a-f3bd1dd4aa61.png)

**Comment by Kronuz** [comment]
The theme works, I'm using it all the time (Sublime Text 3, under OS X). But I haven't tried it under Windows...

**Comment by FichteFoll** [comment]
Surprise, surprise, it works after a reboot. Nothing else changed. Don't ask why.
