### ISSUE TITLE
Icons disappeared after the last upgrade

### ISSUE THREAD

**Issue by AndersonFirmino** [Kronuz/Kronuz-Theme#3]
Hi, the last update, broke the icons in the sidebar. :disappointed:

**Comment by Kronuz** [comment]
I think it actually is a Sublime Text 3 bug.

For the moment you need to add to you settings:

```json
    "kronuz_theme_fileicons": true,
    "kronuz_theme_folder_animation": true,
    "kronuz_theme_tree_indicator": true,
```

**Comment by AndersonFirmino** [comment]
Thanks, these configurations solved the problem :smile:
