### ISSUE TITLE
Retina problem

### ISSUE THREAD

**Issue by taha-moghaddam** [Kronuz/Kronuz-Theme#4]
In retina displays switch panel button which has placed left of the status bar at bottom doesn't shown correctly.

**Comment by Kronuz** [comment]
Could you please provide an image showing the problem and the expected? I'm using mscOS in a MacBook Pro with retina and it shows there fine, I believe.

**Comment by taha-moghaddam** [comment]
Yes, hear you are.
<img width="1440" alt="screen shot 2017-05-17 at 18 23 30" src="https://cloud.githubusercontent.com/assets/3314387/26157329/2def7340-3b2e-11e7-93b1-6b8b3145967f.png">

**Comment by dimitriirybakov** [comment]
It is not just retina problem. I have FullHD monitor and that problem appears too.
![image](https://user-images.githubusercontent.com/16699909/26915707-cd931250-4c2f-11e7-8964-9ac691532ef8.png)

**Comment by Kronuz** [comment]
The path to the icon was wrong. Problem should be fixed now, please reopen of it persists.
